version: "3.9"
services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./data:/db/conf/
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    env_file:
      - .env

  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/api
    ports:
      - "8084:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  dbdata: null
